name: "Run Python Unit Tests"
description: "Run the Python Unit tests"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user virtualenv
    - name: Set PATH for virtualenv
      shell: bash
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Test xapp core
      shell: bash
      run: |
        cd xapp_sdk && mkdir venv_test
        virtualenv -p python3.9 venv_test
        source venv_test/bin/activate
        pip3 install -e .
        if [ -f "requirements.txt" ]; then
          pip3 install -r requirements.txt
        fi
        if [ -f "tests/requirements.txt" ]; then
          pip3 install -r tests/requirements.txt
        fi
        pytest
        deactivate
    - name: Test xapp example
      shell: bash
      run: |
        mkdir venv_test
        virtualenv -p python3.9 venv_test
        source venv_test/bin/activate
        if [ -d "xapp_sdk" ]; then
          pip3 install -e xapp_sdk
        fi
        if [ -f "requirements.txt" ]; then
          pip3 install -r requirements.txt
        fi
        if [ -f "tests/requirements.txt" ]; then
          pip3 install -r tests/requirements.txt
        fi
        pytest tests/
        deactivate

