name: "Run Python Unit Tests"
description: "Run the Python Unit tests"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
    - name: Test xapp_core
      shell: bash
      run: |
        cd xapp_core
        if [ -f "requirements.txt" ]; then
          pip3 install -r requirements.txt
        fi
        if [ -f "tests/requirements.txt" ]; then
          pip3 install -r tests/requirements.txt
        fi
    - name: Run unit tests for xapp core
      shell: bash
      run: |
        cd xapp_core
        pytest
    - name: Test xapp example
      shell: bash
      run: |
        cd example
        if [ -f "requirements.txt" ]; then
          pip3 install -r requirements.txt
        fi
        if [ -f "tests/requirements.txt" ]; then
          pip3 install -r tests/requirements.txt
        fi
    - name: Run unit tests for xapp core
      shell: bash
      run: |
        cd xapp_core
        pytest
    - name: Run unit tests for xapp example
      shell: bash
      run: |
        cd example
        pytest


