name: "Run Python Unit Tests"
description: "Run the Python Unit tests"

inputs:
  github_username:
    description: "User name for GitHub"
    required: true
  github_token:
    description: "Token for GitHub"
    required: true
  framework_version:
    description: "Version of XApp Framework"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip uninstall xapp-lib
        pip3 install pytest==7.1.0

        if [ -f "requirements.txt" ]; then
          export USERNAME=${{inputs.github_username}} && export TOKEN=${{inputs.github_token}} && export VERSION=${{inputs.framework_version}} && pip3 install -r requirements.txt
        fi

        if [ -f "tests/requirements.txt" ]; then
          pip3 install -r tests/requirements.txt
        fi
    - name: Run unit tests
      shell: bash
      run: pytest
      
